--- #YAML:1.0
name:               Algorithm-Functional-BFS
version:            0.01
abstract:           A functional approach to the breadth-first
author:
    - Colin Wetherbee <cww@cpan.org>
license:            mit
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    common::sense:  0
    Test::Class:    0
    Test::More:     0
    Test::Most:     0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
